# Generated by Django 3.2.7 on 2021-10-06 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=200)),
                ('u1', models.IntegerField(default=0)),
                ('u2', models.IntegerField(default=0)),
                ('u3', models.IntegerField(default=0)),
                ('u4', models.IntegerField(default=0)),
                ('u5', models.IntegerField(default=0)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.alumno')),
            ],
        ),
    ]
