# Generated by Django 3.2.7 on 2021-10-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_materias'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='control_number',
            field=models.IntegerField(default=0),
        ),
    ]
