# Generated by Django 3.2.7 on 2021-10-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alumno_control_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materias',
            name='clase',
            field=models.CharField(choices=[('MT', 'Matematicas'), ('FS', 'Fisica'), ('BL', 'Biologia'), ('CL', 'Calculo'), ('ES', 'Español'), ('EN', 'Ingles'), ('HS', 'Historia')], default='MT', max_length=200),
        ),
    ]
